name: web3dart
description: Dart library to connect to Ethereum clients. Send transactions and interact with smart contracts!
version: 3.0.0
homepage: https://pwa.ir
repository: https://github.com/xclud/web3dart

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  pointycastle: ^4.0.0
  sec: ^1.1.1
  http: ">=0.13.1 <2.0.0"
  uuid: ^4.0.0
  json_rpc_2: ^3.0.2
  stream_transform: ^2.1.0
  stream_channel: ^2.1.2
  eip55: ^1.0.3
  eip1559: ^0.6.2
  typed_data: ^1.4.0
  convert: ^3.1.1
  wallet: ^0.0.17

dev_dependencies:
  test: ^1.25.0
  lints: ^5.0.0
