name: web3x
description: Dart library to connect to Ethereum clients. Send transactions and interact with smart contracts!
version: 1.0.4
homepage: https://github.com/AstroxNetwork
repository: https://github.com/AstroxNetwork/web3dart
issue_tracker: https://github.com/AstroxNetwork/web3dart/issues

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  pointycastle: ^3.6.2
  sec: ^1.0.1
  http: ^0.13.5
  uuid: ^3.0.7
  json_rpc_2: ^3.0.2
  stream_transform: ^2.1.0
  stream_channel: ^2.1.1
  eip55: ^1.0.2
  eip1559: ^0.6.1
  typed_data: ^1.3.1
  convert: ^3.1.1
  async: ^2.10.0
  wallet: ^0.0.10
  eth_sig_util: ^0.0.9

dev_dependencies:
  test: ^1.22.0
  lints: ^2.0.0
